version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
  simulator:
    build: ./backend
    command: python simulator.py
    depends_on:
      - backend
    env_file: .env
  frontend:
    build: ./frontend
    env_file: .env
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
    depends_on:
      - backend
